application: hosted-caravel
runtime: python27
api_version: 1
version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

builtins:
- deferred: on
- remote_api: on